# Copyright 2025 D-Wave
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

from dwave.optimization.model import ArraySymbol as _ArraySymbol

class All(_ArraySymbol): ...
class Any(_ArraySymbol): ...
class Max(_ArraySymbol): ...
class Min(_ArraySymbol): ...
class PartialProd(_ArraySymbol): ...
class PartialSum(_ArraySymbol): ...
class Prod(_ArraySymbol): ...
class Sum(_ArraySymbol): ...
