name: Release Note Check

on:
  pull_request:
    types:
      # This is just a reminder, so we won't bother re-running on subsequent updates
      - opened

permissions:
  issues: write  # The comment requires "issue write" permissions
  pull-requests: read  # no write access needed (e.g., we're not applying a label)

jobs:
  check-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check for release note files
        uses: actions/github-script@v9
        with:
          # We use GitHub commands to check the files rather than git in order to
          # avoiding needing to check out the whole repo.
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;

            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner,
                repo,
                pull_number,
                per_page: 100,
              }
            );

            // If the contributor made any changes at all in the releasenotes/
            // directory then we assume we don't need to remind them.
            const hasReleaseNote = files.some(file =>
              file.filename.startsWith("releasenotes/")
            );

            if (hasReleaseNote) {
              core.info("Changes found in releasenotes/");
              return;
            }

            // We'll only raise a reminder if the user has changed something
            // in the dwave/ directory.
            // There are edge cases (e.g., updating supported Python versions)
            // but we don't need to be inclusive for this reminder.
            const madeChanges = files.some(file =>
              file.filename.startsWith("dwave/")
            );

            if (!madeChanges) {
              core.info("No changes found in dwave/");
              return;
            }

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: [
                "Looks like this PR does not have a release note.\n",
                "\n",
                "Only PRs with user-facing changes require a release note, so it's not required.\n",
                "But it's also easy to forget, which is why we added this check!\n",
                "\n",
                "If you're not sure how to add a release note, see ",
                "[CONTRIBUTING.rst](https://github.com/dwavesystems/dwave-optimization/blob/main/CONTRIBUTING.rst)"
              ].join("")
            });
