name: Release Note Check

on:
  pull_request:
    types:
      # This is just a reminder, so we won't bother re-running on subsequent updates
      - opened

permissions:
  issues: write  # The comment requires "issue write" permissions
  pull-requests: read  # no write access needed (e.g., we're not applying a label)

jobs:
  check-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check for release note files
        uses: actions/github-script@v7
        with:
          # We use GitHub commands to check the files rather than git in order to
          # avoiding needing to check out the whole repo.
          # We use reno for release notes so each note is a new file. Hence why we
          # only check for files added.
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;

            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner,
                repo,
                pull_number,
                per_page: 100,
              }
            );

            const hasReleaseNote = files.some(file =>
              file.status === "added" &&
              file.filename.startsWith("releasenotes/")
            );

            if (hasReleaseNote) {
              core.info("Release note found.");
              return;
            }

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: `Looks like this PR does not have a release note.

Only PRs with user-facing changes require a release note, so it's not required.
But it's also easy to forget, which is why we added this check!

If you're not sure how to add a release note, see [CONTRIBUTING.rst](https://github.com/dwavesystems/dwave-optimization/blob/main/CONTRIBUTING.rst)
`
            });
